// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxhrtkzqvklhrvpcspra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4aHJ0a3pxdmtsaHJ2cGNzcHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNjY0NTEsImV4cCI6MjA3MjY0MjQ1MX0.lLaUTXT_eqkaWz-uKNF_azIVJ1rytYxqW0a4d424PKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});